apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: Okta-users
spec:
  identityProviders:
    - mappingMethod: claim
      name: okta
      openID:
        claims:
          email:
          - email
          name:
          - name
          - email
          preferredUsername:
          - preferred_username
          - email
        clientID: < >
        clientSecret:
          name: < >
        extraScopes:
        - email
        - profile
        issuer: < >                       
      type: OpenID
